//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    [DefaultProperty("idCustomer")]
    public partial class Booking : XPObject
    {
        DateTime fcheckInDay;
        [DevExpress.Xpo.DisplayName(@"Dự kiến ngày đến")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat ", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime checkInDay
        {
            get { return fcheckInDay; }
            set { SetPropertyValue<DateTime>(nameof(checkInDay), ref fcheckInDay, value); }
        }
        DateTime fcheckOutDay;
        [DevExpress.Xpo.DisplayName(@"Dự Kiến Ngày Đi")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat ", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime checkOutDay
        {
            get { return fcheckOutDay; }
            set { SetPropertyValue<DateTime>(nameof(checkOutDay), ref fcheckOutDay, value); }
        }
        string fcontent;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Nội dung ")]
        public string content
        {
            get { return fcontent; }
            set { SetPropertyValue<string>(nameof(content), ref fcontent, value); }
        }
        Customer fidCustomer;
        [Association(@"BookingReferencesCustomer")]
        [DevExpress.Xpo.DisplayName(@"Khách Hàng")]
        public Customer idCustomer
        {
            get { return fidCustomer; }
            set { SetPropertyValue<Customer>(nameof(idCustomer), ref fidCustomer, value); }
        }
        [Association(@"BookingDetailReferencesBooking"), Aggregated]
        public XPCollection<BookingDetail> BookingDetails { get { return GetCollection<BookingDetail>(nameof(BookingDetails)); } }
        [Association(@"InvoiceReferencesBooking"), Aggregated]
        public XPCollection<Invoice> Invoices { get { return GetCollection<Invoice>(nameof(Invoices)); } }
    }

}
