//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    public partial class Contract : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fcontractDetails;
        public string contractDetails
        {
            get { return fcontractDetails; }
            set { SetPropertyValue<string>(nameof(contractDetails), ref fcontractDetails, value); }
        }
        string fcontractType;
        public string contractType
        {
            get { return fcontractType; }
            set { SetPropertyValue<string>(nameof(contractType), ref fcontractType, value); }
        }
        long fcontractPrice;
        public long contractPrice
        {
            get { return fcontractPrice; }
            set { SetPropertyValue<long>(nameof(contractPrice), ref fcontractPrice, value); }
        }
        Supplier fsupplierID;
        [Association(@"ContractReferencesSupplier")]
        public Supplier supplierID
        {
            get { return fsupplierID; }
            set { SetPropertyValue<Supplier>(nameof(supplierID), ref fsupplierID, value); }
        }
    }

}
