//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    public partial class Invoice_Service : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Invoice finvoiceID;
        [Association(@"Invoice_ServiceReferencesInvoice")]
        public Invoice invoiceID
        {
            get { return finvoiceID; }
            set { SetPropertyValue<Invoice>(nameof(invoiceID), ref finvoiceID, value); }
        }
        Service fserviceID;
        [Association(@"Invoice_ServiceReferencesService")]
        public Service serviceID
        {
            get { return fserviceID; }
            set { SetPropertyValue<Service>(nameof(serviceID), ref fserviceID, value); }
        }
        ushort fquantity;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public ushort quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<ushort>(nameof(quantity), ref fquantity, value); }
        }
        decimal fprice;
        [DevExpress.Xpo.DisplayName(@"Giá")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ## ### ###")]
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ## ### ###")]
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [PersistentAlias("ToDecimal([quantity]) * [price]")]
        public decimal amount
        {
            get { return (decimal)(EvaluateAlias(nameof(amount))); }
        }
    }

}
