//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    [DefaultProperty("priceRoom")]
    public partial class Invoice : DevExpress.Persistent.BaseImpl.BaseObject
    {
        decimal fpriceRoom;
        [DevExpress.Xpo.DisplayName(@"Giá phòng")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ## ### ###")]
        public decimal priceRoom
        {
            get { return fpriceRoom; }
            set { SetPropertyValue<decimal>(nameof(priceRoom), ref fpriceRoom, value); }
        }
        decimal fpriceService;
        [DevExpress.Xpo.DisplayName(@"Giá dịch vụ khác")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "#### #### ####"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "#### #### ####")]
        public decimal priceService
        {
            get { return fpriceService; }
            set { SetPropertyValue<decimal>(nameof(priceService), ref fpriceService, value); }
        }
        DateTime fDate;
        [DevExpress.Xpo.DisplayName(@"Ngày")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        string fpaymentStatus;
        [DevExpress.Xpo.DisplayName(@"Trạng thái thanh toán")]
        public string paymentStatus
        {
            get { return fpaymentStatus; }
            set { SetPropertyValue<string>(nameof(paymentStatus), ref fpaymentStatus, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "#### #### ####"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "#### #### ####")]
        [DevExpress.Xpo.DisplayName(@"Tổng tiền")]
        [PersistentAlias("[priceRoom] + [priceService]")]
        public decimal amount
        {
            get { return (decimal)(EvaluateAlias(nameof(amount))); }
        }
        Booking fidBooking;
        [Association(@"InvoiceReferencesBooking")]
        public Booking idBooking
        {
            get { return fidBooking; }
            set { SetPropertyValue<Booking>(nameof(idBooking), ref fidBooking, value); }
        }
        [Association(@"PaymentsReferencesInvoice")]
        public XPCollection<Payments> PaymentsCollection { get { return GetCollection<Payments>(nameof(PaymentsCollection)); } }
        [Association(@"Invoice_ServiceReferencesInvoice"), Aggregated]
        public XPCollection<Invoice_Service> Invoice_Services { get { return GetCollection<Invoice_Service>(nameof(Invoice_Services)); } }
    }

}
