//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    public partial class Items : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fitemName;
        public string itemName
        {
            get { return fitemName; }
            set { SetPropertyValue<string>(nameof(itemName), ref fitemName, value); }
        }
        double fitemPrice;
        public double itemPrice
        {
            get { return fitemPrice; }
            set { SetPropertyValue<double>(nameof(itemPrice), ref fitemPrice, value); }
        }
        string fcategory;
        public string category
        {
            get { return fcategory; }
            set { SetPropertyValue<string>(nameof(category), ref fcategory, value); }
        }
        long fquantityInStock;
        public long quantityInStock
        {
            get { return fquantityInStock; }
            set { SetPropertyValue<long>(nameof(quantityInStock), ref fquantityInStock, value); }
        }
        Supplier fsupplierID;
        [Association(@"ItemsReferencesSupplier")]
        public Supplier supplierID
        {
            get { return fsupplierID; }
            set { SetPropertyValue<Supplier>(nameof(supplierID), ref fsupplierID, value); }
        }
        Staff fstaffID;
        [Association(@"ItemsReferencesStaff")]
        public Staff staffID
        {
            get { return fstaffID; }
            set { SetPropertyValue<Staff>(nameof(staffID), ref fstaffID, value); }
        }
        [Association(@"TransactionsReferencesItems"), Aggregated]
        public XPCollection<Transactions> TransactionsCollection { get { return GetCollection<Transactions>(nameof(TransactionsCollection)); } }
    }

}
