//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    [DefaultProperty("paymentMethod")]
    public partial class Payments : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Invoice finvoiceID;
        [Association(@"PaymentsReferencesInvoice")]
        public Invoice invoiceID
        {
            get { return finvoiceID; }
            set { SetPropertyValue<Invoice>(nameof(invoiceID), ref finvoiceID, value); }
        }
        string fpaymentMethod;
        [DevExpress.Xpo.DisplayName(@"Payment method")]
        public string paymentMethod
        {
            get { return fpaymentMethod; }
            set { SetPropertyValue<string>(nameof(paymentMethod), ref fpaymentMethod, value); }
        }
        DateTime fpaymentDate;
        [DevExpress.Xpo.DisplayName(@"Payment date")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime paymentDate
        {
            get { return fpaymentDate; }
            set { SetPropertyValue<DateTime>(nameof(paymentDate), ref fpaymentDate, value); }
        }
        decimal famountPaid;
        [DevExpress.Xpo.DisplayName(@"Amount paid")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ## ### ###")]
        public decimal amountPaid
        {
            get { return famountPaid; }
            set { SetPropertyValue<decimal>(nameof(amountPaid), ref famountPaid, value); }
        }
    }

}
