//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

 
    public partial class Room : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fnumberRoom;
        [DevExpress.Xpo.DisplayName(@"Mã Phòng")]
        public short numberRoom
        {
            get { return fnumberRoom; }
            set { SetPropertyValue<short>(nameof(numberRoom), ref fnumberRoom, value); }
        }
        string ftypeRoom;
        [DevExpress.Xpo.DisplayName(@"Loại Phòng")]
        public string typeRoom
        {
            get { return ftypeRoom; }
            set { SetPropertyValue<string>(nameof(typeRoom), ref ftypeRoom, value); }
        }
        string fdescription;
        [DevExpress.Xpo.DisplayName(@"Mô Tả Tiện Ích")]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        string fstatus;
        [ColumnDefaultValue("Trống")]
        [DevExpress.Xpo.DisplayName(@"Tình Trạng")]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>(nameof(status), ref fstatus, value); }
        }
        decimal fprice;
        [DevExpress.Xpo.DisplayName(@"Giá")]
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        [Association(@"BookingDetailReferencesRoom"), Aggregated]
        public XPCollection<BookingDetail> BookingDetails { get { return GetCollection<BookingDetail>(nameof(BookingDetails)); } }
    }

}
