//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    [DefaultProperty("typeService")]
    public partial class Service : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ftypeService;
        [DevExpress.Xpo.DisplayName(@"Type service")]
        public string typeService
        {
            get { return ftypeService; }
            set { SetPropertyValue<string>(nameof(typeService), ref ftypeService, value); }
        }
        decimal fprice;
        [DevExpress.Xpo.DisplayName(@"Price")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ## ### ###")]
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        [Association(@"Invoice_ServiceReferencesService"), Aggregated]
        public XPCollection<Invoice_Service> Invoice_Services { get { return GetCollection<Invoice_Service>(nameof(Invoice_Services)); } }
    }

}
