//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    [DefaultProperty("fullName")]
    public partial class Staff : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ffullName;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Họ Tên")]
        public string fullName
        {
            get { return ffullName; }
            set { SetPropertyValue<string>(nameof(fullName), ref ffullName, value); }
        }
        string faddress;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Địa Chỉ")]
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        string fphone;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Số Điện Thoại")]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string femail;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Email")]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        DateTime fdateOfBirth;
        [DevExpress.Xpo.DisplayName(@"Ngày Sinh")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy}")]
        public DateTime dateOfBirth
        {
            get { return fdateOfBirth; }
            set { SetPropertyValue<DateTime>(nameof(dateOfBirth), ref fdateOfBirth, value); }
        }
        string fposition;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Chức Vụ")]
        public string position
        {
            get { return fposition; }
            set { SetPropertyValue<string>(nameof(position), ref fposition, value); }
        }
        DateTime fstartDate;
        [DevExpress.Xpo.DisplayName(@"Ngày Vào Làm")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy}")]
        public DateTime startDate
        {
            get { return fstartDate; }
            set { SetPropertyValue<DateTime>(nameof(startDate), ref fstartDate, value); }
        }
        decimal fsalary;
        [DevExpress.Xpo.DisplayName(@"Lương Cơ Bản")]
        public decimal salary
        {
            get { return fsalary; }
            set { SetPropertyValue<decimal>(nameof(salary), ref fsalary, value); }
        }
        [Association(@"CustomerReferencesStaff"), Aggregated]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CounterpartyReferencesStaff"), Aggregated]
        public XPCollection<Counterparty> Counterparties { get { return GetCollection<Counterparty>(nameof(Counterparties)); } }
        [Association(@"ItemsReferencesStaff"), Aggregated]
        public XPCollection<Items> ItemsCollection { get { return GetCollection<Items>(nameof(ItemsCollection)); } }
        [Association(@"TransactionsReferencesStaff"), Aggregated]
        public XPCollection<Transactions> TransactionsCollection { get { return GetCollection<Transactions>(nameof(TransactionsCollection)); } }
    }

}
