//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    public partial class Supplier : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fsupplierName;
        public string supplierName
        {
            get { return fsupplierName; }
            set { SetPropertyValue<string>(nameof(supplierName), ref fsupplierName, value); }
        }
        string fcontractInfo;
        public string contractInfo
        {
            get { return fcontractInfo; }
            set { SetPropertyValue<string>(nameof(contractInfo), ref fcontractInfo, value); }
        }
        string fdeliveryHistory;
        public string deliveryHistory
        {
            get { return fdeliveryHistory; }
            set { SetPropertyValue<string>(nameof(deliveryHistory), ref fdeliveryHistory, value); }
        }
        [Association(@"ContractReferencesSupplier"), Aggregated]
        public XPCollection<Contract> Contracts { get { return GetCollection<Contract>(nameof(Contracts)); } }
        [Association(@"ItemsReferencesSupplier"), Aggregated]
        public XPCollection<Items> ItemsCollection { get { return GetCollection<Items>(nameof(ItemsCollection)); } }
    }

}
