//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ManageHotel.Module.BusinessObjects.Staff
{

    public partial class Transactions : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ftransactionType;
        public string transactionType
        {
            get { return ftransactionType; }
            set { SetPropertyValue<string>(nameof(transactionType), ref ftransactionType, value); }
        }
        DateTime ftransactionDate;
        public DateTime transactionDate
        {
            get { return ftransactionDate; }
            set { SetPropertyValue<DateTime>(nameof(transactionDate), ref ftransactionDate, value); }
        }
        long fquantity;
        public long quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<long>(nameof(quantity), ref fquantity, value); }
        }
        Items fitemID;
        [Association(@"TransactionsReferencesItems")]
        public Items itemID
        {
            get { return fitemID; }
            set { SetPropertyValue<Items>(nameof(itemID), ref fitemID, value); }
        }
        Staff fstaffID;
        [Association(@"TransactionsReferencesStaff")]
        public Staff staffID
        {
            get { return fstaffID; }
            set { SetPropertyValue<Staff>(nameof(staffID), ref fstaffID, value); }
        }
    }

}
